Enable SSL for all server
phpmyadmin/docker pull request #441
Opened 2024-08-01 09:20 UTC by TasdidurRahman

2024-08-01 09:57 UTC, williamdes commented
> wrong upstream

If you want you can contribute adding support for SSL via ENVs
See: https://github.com/phpmyadmin/docker/issues?q=is%3Aissue+is%3Aopen+SSL

2024-08-16 05:58 UTC, TasdidurRahman commented
hi @williamdes, can you review this?

2024-08-19 09:23 UTC, williamdes requested changes
Please update https://github.com/phpmyadmin/docker/blob/master/config.inc.php
And run ./update.sh

Can you also add documentation on the README ?
It is unclear how to use this

`PMA_SSLS="0,1"` is maybe not very user friendly

2024-08-19 09:52 UTC, TasdidurRahman commented
> PMA_SSLS="0,1" is maybe not very user friendly
imo this is better to keep it simple as we are not using CA rn. still we are open for suggestion! 
@williamdes

2024-08-19 10:16 UTC, williamdes requested changes
Okay, I did not see that other ENVs have the same logic
Please add documentation to the README and say the variable works in the same way that PMA_PORTS works

2024-08-19 11:39 UTC, williamdes commented on README.md
> +* ``PMA_SSLS`` - comma separated list of 0 and 1 defining ssl usage for corresponding MySQL servers
```suggestion
* ``PMA_SSL`` - Enable ssl usage for the MySQL connection
* ``PMA_SSLS`` - comma separated list of `0` and `1` defining ssl usage for the corresponding MySQL connections
```
Please move this at the end of the list

2024-08-19 11:46 UTC, TasdidurRahman commented on README.md
> +* ``PMA_SSLS`` - comma separated list of 0 and 1 defining ssl usage for corresponding MySQL servers
moved

2024-08-19 11:46 UTC, TasdidurRahman commented on README.md
> +Set the variable ``PMA_SSL`` to '1' and enable ssl usage from phpmyadmin to mysql server. The default value is 0. Variable ``PMA_SSLS`` can be used as a comma seperated sequence of 0 and 1 where mult
updated

2024-08-19 17:52 UTC, MauricioFauth approved these changes

2024-08-20 18:00 UTC, merged

2024-08-20 18:00 UTC, williamdes reviewed
Thank you !

2024-08-20 18:45 UTC, williamdes commented
I sent your changes to the official registry: https://github.com/docker-library/official-images/pull/17398

2025-01-04 00:02 UTC, williamdes commented on README.md
> +- `PMA_SSLS`
@TasdidurRahman I am considering a revert of the two lines
It makes no sense to read 1 and 0 from a file
What do you think ?

2025-01-14 13:58 UTC, williamdes commented on README.md
> +- `PMA_SSLS`
Reverted as 577a94fda60fbd1bb13247531c1783db9c51a64b

2025-01-23 10:34 UTC, TasdidurRahman commented on README.md
> +- `PMA_SSLS`
sorry for late reply, LGTM

2025-01-23 10:41 UTC, williamdes commented on README.md
> +- `PMA_SSLS`
Thank you